modded_key = "modded"
is_display_column = "isDisplayColumn"
default_value = "default"
timestamp_str = "timestamp"
ui_input_data = "data"
worksheets_df_key = "worksheets"
worker_index = "worker_index"
is_resuming_shift = "isResumingShift"

connection_rating_radio_index_key = "connection-rating"
radio_str_key = "radio-key"
notes_key = "notes"
cached_notes_key = "cached-notes"
connections_str_key = "connections"