#page constants
CURRENT_PAGE = "currentpage"
ENRTY = "entry"
START_SHIFT = "startshift"
PROMPTS = "prompts"
WORKERS = "workers"

workers_table = "workers"
workers_table_name = "workers"
workers_label_name = "workers"
workers_key_column_name = "name"
workers_key = "name"
worker_is_working = "isworking"
is_display_column = "is_display_column"
default_value = "default"
workers_columns_names = [workers_key_column_name, "contact", worker_is_working]
workers_dataframe_key_name = "workers_dataframe"
workers_item_name = "workers"

prompts_table = "prompts"
prompts_table_name = "prompts"
prompts_label_name = "prompts"
prompts_column_name = "prompts"
prompts_dataframe_key_name = "prompts_dataframe"
prompts_item_name = "prompts"
