#page constants
CURRENT_PAGE = "currentpage"
ENRTY = "entry"
START_SHIFT = "startshift"
QUESTIONS = "questions"
WORKERS = "workers"

workers_table = "workers"
workers_table_name = "workers"
workers_label_name = "workers"
workers_column_name = "workers"
workers_dataframe_key_name = "workers_dataframe"
workers_item_name = "workers"
worker_input_key = "workers_input"

questions_table = "questions"
questions_table_name = "questions"
questions_label_name = "questions"
questions_column_name = "questions"
questions_dataframe_key_name = "questions_dataframe"
questions_item_name = "questions"
question_input_key = "questions_input"
